### ISSUE TITLE
parsing go.mod: unexpected module path "copy"

### ISSUE THREAD

**Issue by kbirk** [otiai10/copy#10]
When attempting to use go modules with this package I get:

```
go: github.com/otiai10/copy@v0.0.0-20190225084637-eb7e34b5fa7d: parsing go.mod: unexpected module path "copy"
```

I suspect it has to do with the `go.mod` module being declared as `copy` rather than the full package name:

Ex.

```
module copy

require (
	bou.ke/monkey v1.0.1 // indirect
	github.com/otiai10/mint v1.2.1
)
```

rather than:

```
module github.com/otiai10/copy

require (
	bou.ke/monkey v1.0.1 // indirect
	github.com/otiai10/mint v1.2.1
)
```

**Comment by otiai10** [comment]
Thanks! Interesting. I guess it's because that's not me who added the mod 😊

**Comment by otiai10** [comment]
OK, thanks. it's reproduced on my machine.

**Comment by otiai10** [comment]
@kbirk Thank you very much!
https://github.com/otiai10/copy/commit/b872ce7639fa969350e7fef6c4a2c1c378d5b0e5
