### ISSUE TITLE
Add config to rename file

### ISSUE THREAD

**Issue by tomaswarynyca** [otiai10/copy#109]
I have several files embedded (waiting for the PR for the support)
When copying them it would be nice if I can edit the name.
Would it be possible to add a function in the configuration to do this?
What do you think? @otiai10

**Comment by otiai10** [comment]
In my opinion, renaming files is not in the scope of this software.
I'd like to know the specific use case of this feature you imagine.

**Comment by tomaswarynyca** [comment]
In my case I have embedded files (thanks for the support).
These files have double extensions (so that the go compiler doesn't go crazy).
So I have to remove the double extension when copying them.
e.g.  main.go.stub to main.go

**Comment by tomaswarynyca** [comment]
@otiai10 did you have time to analyse this functionality?
