### ISSUE TITLE
Remove symbolic link from test case 03

### ISSUE THREAD

**Issue by farshidtz** [otiai10/copy#11]
Hi,

There is a symbolic link from `testdata/case03/case01` to `./testdata/case01`. When vendoring the package, the dependency manager vendors the link but not the case01 directory, breaking the link.

I understand that you need the link for your tests, but would it be possible to generate it during your tests instead? The broken link causes problems if one tries to copy it or in Windows OS.

Thanks

**Comment by otiai10** [comment]
@farshidtz Thanks!

Check https://github.com/otiai10/copy/commit/c7381036ced2f01eaf44354b320b47a6874aef0b and make sure it works on your machine. Thank you
