### ISSUE TITLE
Symlink copy option to copy a symlink even if the destination of the symlink does not exists

### ISSUE THREAD

**Issue by ducktype** [otiai10/copy#111]
Currently symlink are copied only if the path pointed by the symlink exists, will be useful to have an option to copy the symlink anyway

**Comment by otiai10** [comment]
tell me the reason why it would be helpful

**Comment by ducktype** [comment]
My use case is to copy a list of files/symlinks that are known to be consistent (eg symlinks point to files in the list) but are out of order (Eg the symlinks could be before the pointed file in the list)

**Comment by otiai10** [comment]
ah, interesting. let me think about it
