### ISSUE TITLE
Question: backwards compatibility 1.7.0 to 1.9.0+?

### ISSUE THREAD

**Issue by andoks** [otiai10/copy#118]
Version [1.9.0](https://github.com/otiai10/copy/releases/tag/v1.9.0) broke backwards compatibility of the library, meaning other projects using it stopped compiling if someone upgraded the github.com/otiai10/copy package, either upgrading "by accident", or if they include a different package that has a minimum version dependency on github.com/otiai10/copy that is v1.9.0 or newer.

One tool that relies on github.com/otiai10/copy is [go-licenses](https://github.com/google/go-licenses/blob/v1.6.0/go.mod#L13), which stopped compiling after I inadvertently upgraded the copy dependency (I am only a user of the tool). 

I am mostly posting this for posterity, and to bring the issue up since I couldn't see anything about it in the issue tracker.

One way to restore backwards compatibility I think, could be to restore the copy function's previous skip type, and add a new function that uses the [Options-pattern (option 3)](https://golang.cafe/blog/golang-functional-options-pattern.html) to be able to extend the function with new options in the future without breaking backwards compatibility. It is also possible to mark the old copy function as [deprecated](https://github.com/golang/go/wiki/Deprecated)

This will of course break users of v1.9.0 and v1.11.0, but assuming those users are fewer than users of the older versions might be reasonable, and their software is probably earlier in the development/in active development meaning they would be relatively quick in fixing the issue.

**Comment by andoks** [comment]
I did not mean that v1.11.0 breaks backwards-compatibility with 1.9. Rather that the 1.9 (as announced in the release note) breaks compatibility with the earlier versions, and I am asking if there is a possibility of restoring backwards compatibility with those previous versions in some way, and if you (the maintainers) do not want to do this, this issue documents this for posterity in case others have the same issue.

**Comment by otiai10** [comment]
Thank you for your comment on this.
As of now, I understand the release note describes the breaking change explicitly and that's the way we should go.

* https://github.com/otiai10/copy/releases
* https://github.com/otiai10/copy/releases/tag/v1.9.0

Before, we had similar issue:

* https://github.com/google/go-licenses/issues/21
* https://github.com/otiai10/copy/releases/tag/v1.2.0

**Comment by otiai10** [comment]
At the same time, your concern makes sense as well.
What do you think if we could add the latest breaking change on the top README?

**Comment by andoks** [comment]
Unfortunately that will not stop the breaking of projects using this library.

In general after tagging version 1.0.0 of a library, any breaking change to the library should be tagged as a bump in the major version (i.e v2.0.0, v3.0.0), and if the library is in active development receiving breaking changes regularly, the library should stay in the as v0.x.x (as I think the go version handling treats v0 in a special way with regards to updates) - see [go.dev - Module version numbering](https://go.dev/doc/modules/version-numbers) for the details.

The reason the break in v1.9.0 caused issue for us was that we use a [tools.go approach](https://www.jvt.me/posts/2022/06/15/go-tools-dependency-management/) to version our build and CI tooling, where we execute the tools using `go run` (e.g `go run github.com/google/go-licenses ...` and when we did a bump in library versions, the go tool assumes that minor and patch versions are OK to upgrade because they are supposed to be backwards compatible (according to the go module best practice described in the above source).

Documenting the breakage might be an improvement re discoverability though.

**Comment by otiai10** [comment]
Thank you, and I totally got your point.

Thank you, and I completely understand your point.

Yes, you are correct. We should have adhered to the semver approach to ensure that your projects continue functioning without concern for the versions of dependencies.

I appreciate you documenting this, and I am committed to following the semver approach in future instances, as you have highlighted. Please be aware that I will maintain the current version of this package as it stands, as I have already made the decision to include a breaking change in v1.9.0.

FYI
* https://github.com/google/go-licenses/pull/203
    * https://github.com/google/go-licenses/commit/e41525ccefa8f75f4b790debd8a674ede5b49190#diff-63d2514e96da76ad8bd5c2460f4ea67c0a6c6ba1055a8890b7ec0c686bcc183fL124-L127

Thank you again for caring this

**Comment by andoks** [comment]
I totally understand that. Thank you for making the module available for us all to use 😊
