### ISSUE TITLE
Use of bou.ke/monkey -- unneeded?

### ISSUE THREAD

**Issue by bt** [otiai10/copy#12]
I've seen that there's a reference to `bou.ke/monkey` in the `go.mod` but I'm unsure where it's being used.

The license for `monkey` pretty much disallows anyone from using it, which in term means that no one can use your library either. See [here](https://github.com/bouk/monkey/pull/18) and [here](https://github.com/bouk/monkey/blob/master/LICENSE.md) for more information.

Is it needed, or is can we just remove it and keep this library as MIT? 😄

**Comment by otiai10** [comment]
@bt Thank you! Big problem! I'm gonna remove it
