### ISSUE TITLE
Failed to symlink if file already exists

### ISSUE THREAD

**Issue by starzation** [otiai10/copy#132]
Like the tittle said if the file is already exists (in destination folder) it will throw 'symlink error file exists'

There already a quick patch in vinegarhq/vinegar#322, Should the patch belong here or theres?

Issue (For log and more info): vinegarhq/vinegar#321
Code: [vinegarhq/vinegar/internal/dirs/copy.go](https://github.com/vinegarhq/vinegar/blob/master/internal/dirs/copy.go#L11)

**Comment by otiai10** [comment]
Regarding this https://github.com/vinegarhq/vinegar/pull/322 and [the change](https://github.com/vinegarhq/vinegar/pull/322/files), it seems you're trying to copy `Overlay` to `dest`. Is it right?

We assume that users can check existence or properties of the root argument, the first argument the users give to `cp.Copy` func, by theirselves.

`OnError` or `OnSymlink` is to define behavior to handle something **inside the folders**, not the root folders.

Therefore, if you are talking about the root folders, you should separate the check before calling `cp.Copy`.

----

If my quick view above doesn't answer your question, let me ask you some clarification questions:

Given `what 1`, `what 2` do you expect?
`What 3` did you see?
`What 4` is your proposal?

**Comment by starzation** [comment]
> Regarding this [vinegarhq/vinegar#322](https://github.com/vinegarhq/vinegar/pull/322) and [the change](https://github.com/vinegarhq/vinegar/pull/322/files), it seems you're trying to copy `Overlay` to `dest`. Is it right?
Yes that right.

Look like this is not the lib issue right? This mean we need to check if the file is already exists first if not then we call `cp.Copy` right? Since by default `cp.Copy` doesn't check if the file already exists and trying to copy the file

For more information:
`Overlay` and `dest` is root folder and we trying to copy **file inside `Overlay`**  into `dest` folder.

**Comment by starzation** [comment]
Thank you for your clarification. Also thank you for your assistance.

**Comment by apprehensions** [comment]
If i read `copy` behavior right, `copy` copies file no matter if the files exist in the destination directory, so why is the same not done for symlinks?

I expected `copy` to copy files from a source directory to a destination directory recursively, no matter if files are present or not in the destination.

**Comment by otiai10** [comment]
@apprehensions Thank you for your comment.

Out discussion point is about "root" and "children".
When we talk about "root", it's users' responsibility to check the validity.

When we talk about "children" under the root, we need a basic philosophy and some options to let users control the behavior.

**Comment by apprehensions** [comment]
Why are symlinks an exception?

**Comment by otiai10** [comment]
Clarification:
Are we talking about this?
https://github.com/otiai10/copy/blob/1b0f2555a418af91c68cbd6c233a15e5e771ca96/copy.go#L314-L325

**Comment by apprehensions** [comment]
Yes, it seems copying the source symlinks even if it's links to somewhere that does not exist. It would hr better if the symlinks gets copied to the destination regardless if it does not exist much like regular files

**Comment by otiai10** [comment]
I think I got your point:

* We are talking about "children" entries, not about "root" entries.
* `copy.Copy` should not return error even if the destination of symlink already exists. (Update the symlink as of the source)

Correct me if I'm understanding wrong.

**Comment by apprehensions** [comment]
Yes, the children (destination, copy) symlink should have the same behavior as copying regular files.

I apologize if I was explaining incorrectly.

**Comment by otiai10** [comment]
Can you please open another issue for this?

**Comment by apprehensions** [comment]
@starzation can you confirm #145 fixes your problem?
