### ISSUE TITLE
add an option to deep-copy symlinks

### ISSUE THREAD

**Issue by yasushi-saito** [otiai10/copy#15]
Can we have an option to copy symlinks? I'm imagining something like:

```go
Opts struct {
  // Called if a symlink is found. If this function returns false, 
  // Copy copies the symlink itself. Else, Copy() follows the link.
  // If FollowSymlink=nil, Copy never follows symlinks.
  FollowSymlink func(path string) bool
}
```

func Copy(src, dest string, opt... Opts) error;

I can create a pull request if it looks good.

**Comment by otiai10** [comment]
Can you please list up expected usecases of this option first?

**Comment by otiai10** [comment]
From my perspective, there are 3 usecases when it comes to symlink:

1. Hard copy
2. Soft copy (create a link to the same resource)
3. Ignore

What do you think?

**Comment by yasushi-saito** [comment]
Yes, the only feature I need now is deep-copies (i.e., follow all symlinks). So we can just have

type Opt struct { FollowSymlink bool }

I can't think a use case to ignore symlinks.

**Comment by otiai10** [comment]
OK, then

1. Hard copy
2. Soft copy (follow) ← what you want
3. Others (Skip?)

Is it right?

**Comment by otiai10** [comment]
hmm, confusing... I'm still not sure what you want since your test cases are not descriptive enough and even failing.
