### ISSUE TITLE
Symlinks don't resolve relative paths properly

### ISSUE THREAD

**Issue by claassen** [otiai10/copy#26]
When copying a directory to another directory that is at a different path level, symlinks that resolve to relative paths fail to be copied as the source path of the symlink is not resolved to the absolute path.

Example:

Source folder:
src/
  a/
    someFile
  b/
    someFile (symlink to '../a/someFile')

`Copy("src", "dest")` 

will work fine, however:

`Copy("src", "../dest") fails with:

readlink "dest/a/someFile": no such file or directory

What is happening as when using os.ReadLink, e.g.:

```
src, _ := os.Readlink("src/b/someFile")
```

src is return as "../a/someFile"

but it should really be expanded to the full path of "src/a/someFile", e.g. using filepath.Abs(src)

**Comment by otiai10** [comment]
@claassen is this closed?

**Comment by LorisFriedel** [comment]
Hello!

I'm also facing this issue, is there any workaround to have relative path resolved properly on symlinks?

Thank you!

**Comment by nick-stroud** [comment]
Can we reopen this issue? Any progress on this? This is blocking https://github.com/GoogleCloudPlatform/hpc-toolkit from using symlinks.
