### ISSUE TITLE
Symbolic links are not handled correctly

### ISSUE THREAD

**Issue by fumoboy007** [otiai10/copy#3]
Symbolic links need to be handled separately from directories and regular files.

## Example Failure

- myDir
- mySymlink → myDir

Calling `Copy("mySymlink", "mySymlink2")` fails because the library tries to read the file like a regular file, which fails because the symbolic link is pointing to a directory.

## Fix

The fix is to check whether a file is a symbolic link and if so, call a new function that simply copies the link to the destination.

**Comment by otiai10** [comment]
Thanks.

@otiai10
cf https://golang.org/pkg/os/#Lstat
