### ISSUE TITLE
Adding Replace option

### ISSUE THREAD

**Issue by mariaefi29** [otiai10/copy#30]
Dear @otiai10,

What do you think of adding copy with replace option (WithReplace, true or false)? 

I noticed that if we copy one directory to another, it preserves old files as the way they are. 

I think, it would be a nice feature to have, if you need to replace the entire destination directory by the source one.

By the way, nice package!

**Comment by otiai10** [comment]
Thanks,

Do you mean simply like this?

```
rm -rf dest
cp -r src dest
```

in Go

```go
os.RemoveAll("dest")
copy.Copy("src", "dest")
```

**Comment by mariaefi29** [comment]
Not really, sorry for not clarifying properly.

For example, we have very complex structures. src directory can contain folders with different folders and dest directory as well. For example:

```
src: src/A/b/<different files>, src/A/c/<different files>, src/B/d/<different files>, src/B/e/<different files>
dest: dest/A/c/<different files>, dest/B/e/<different files>
```

When I use `copy.Copy(src, dest)`, I would like that it will replace  `src/A/c/<different files>, src/B/e/<different files>`  by dest contents completely. But it leaves files in src (in A/c and B/e) that were not present in dest. It would be very useful when we don't know the structure of dest directory.

**Comment by otiai10** [comment]
At that point, it sounds like `merge`, rather than `copy`. What do you think?

**Comment by mariaefi29** [comment]
To be honest, I think that what copy does now is merging. It sort of combines old and new files together. But we need replacing option I guess. That the last sub directory will be replaced. 

In my project I did a workaround like that:
```
var dirPattern = regexp.MustCompile(`^` + tempDir + `\/[A-Z]{3}(\/[A-Z]{3})?\/\w{4,}$`)

func replaceDirectory(src, dst string) error {
	return filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if !info.IsDir() {
			return nil
		}

		if !dirPattern.MatchString(path) {
			return nil
		}

		filePath := filepath.Join(dst, strings.TrimPrefix(path, src))
		_ = os.RemoveAll(filePath)

		err = copy.Copy(path, filePath)
		if err != nil {
			return fmt.Errorf("copy temp dir: %w", err)
		}

		return nil
	})
}
```

but for me it looks ugly :))) But I don't see any other solution yet)

**Comment by otiai10** [comment]
> To be honest, I think that what copy does now is merging.

I checked the current behavior, and yes you are right, it's merging.

> In my project I did a workaround like that:

As I understand it, you want to replace all folders **in a specific depth** without preserving existing files under them.
Is it right?

**Comment by mariaefi29** [comment]
Yes, that's right :) Do you think it is possible to do it in your package?

**Comment by otiai10** [comment]
Yes, it is possible.
Let me think what it should be.

**Comment by otiai10** [comment]
@mariaefi29  Please validate following statement.

# Given

`src` dir:
```
src
├── A
│   ├── b
│   │   ├── 001.txt
│   │   └── 002.txt
│   └── c
│       ├── 003.txt
│       └── 004.txt
└── B
    ├── d
    │   ├── 005.txt
    │   └── 006.txt
    └── e
        ├── 007.txt
        └── 008.txt

6 directories, 8 files
```

existing `dest` dir:
```
dest
├── A
│   └── c
│       ├── 109.txt
│       └── 110.txt
└── B
    └── e
        ├── 111.txt
        └── 112.txt

4 directories, 4 files
```

# When

```go
copy.Copy("src", "dest")
```

# I want

```
dest
├── A
│   ├── b
│   │   ├── 001.txt
│   │   └── 002.txt
│   └── c
│       ├── 003.txt
│       └── 004.txt
└── B
    ├── d
    │   ├── 005.txt
    │   └── 006.txt
    └── e
        ├── 007.txt
        └── 008.txt

6 directories, 8 files
```

# But I have

```
dest
├── A
│   ├── b
│   │   ├── 001.txt
│   │   └── 002.txt
│   └── c
│       ├── 003.txt
│       ├── 004.txt
│       ├── 109.txt
│       └── 110.txt
└── B
    ├── d
    │   ├── 005.txt
    │   └── 006.txt
    └── e
        ├── 007.txt
        ├── 008.txt
        ├── 111.txt
        └── 112.txt

6 directories, 12 files
```

**Comment by mariaefi29** [comment]
@otiai10 Hi!

Yes, thats right! I think merge is also great, but option as total replacement can come in handy when you don't know name of directories in dest.

**Comment by otiai10** [comment]
@mariaefi29 what do you expect when following structures are given?

# Given

```
src
├── A
│   ├── b
│   │   ├── 001.txt
│   │   └── 002.txt
│   └── c
│       ├── 003.txt
│       └── 004.txt
└── B
    ├── d
    │   ├── 005.txt
    │   └── 006.txt
    └── e
        ├── 007.txt
        └── 008.txt

6 directories, 8 files
```

```
dest
├── A
│   └── c
│       ├── 109.txt
│       └── 110.txt
└── B
    ├── e
    │   ├── 111.txt
    │   └── 112.txt
    └── f
        ├── 113.txt
        └── 114.txt

5 directories, 6 files
```

# Whan

```go
copy.Copy("src", "dest", opt)
```

# What do you expect?

**Comment by mariaefi29** [comment]
@otiai10 With that replacing option I would expect 
```
dest
├── A
│   ├── b
│   │   ├── 001.txt
│   │   └── 002.txt
│   └── c
│       ├── 003.txt
│       └── 004.txt
└── B
    ├── d
    │   ├── 005.txt
    │   └── 006.txt
    └── e
        ├── 007.txt
        └── 008.txt

6 directories, 8 files
```

**Comment by otiai10** [comment]
Check this commit. Thanks
https://github.com/otiai10/copy/pull/37/commits/5954fcb157e2b44c9f5c33e3dccf6d92a7a037cb

**Comment by mariaefi29** [comment]
Thank you so much! 

I am a little swamped this week( Can I get back to you next week please on that?

**Comment by otiai10** [comment]
Take your time. Any feedback would be welcomed.

**Comment by mariaefi29** [comment]
Thank you very much again!

**Comment by nikhiljiddigi** [comment]
Dear @otiai10 ,

I have a similar issue but in my case it is directories.

**Given**
`src` dir:

```
src
├── A
│   ├── b
│   │   ├── 001.txt
│   │   └── 002.txt
│   └── f
│       ├── 003.txt
│       └── 004.txt
└── B
    └── d
        ├── 007.txt
        └── 008.txt
5 directories, 6 files

```
existing `dest` dir:

```
dest
├── A
│   ├── b
│   │   ├── 001.txt
│   │   └── 002.txt
│   └── c
│       ├── 109.txt
│       └── 110.txt
└── B
    └── e
        ├── 111.txt
        └── 112.txt

5 directories, 6 files
```
**When**
`copy.Copy("src", "dest")
`

**I want**
```
dest
├── A
│   ├── b
│   │   ├── 001.txt
│   │   └── 002.txt
│   └── f
│       ├── 003.txt
│       └── 004.txt
└── B
    └── d
        ├── 007.txt
        └── 008.txt
5 directories, 6 files
```

**But I have**
```
dest
├── A
│   ├── b
│   │   ├── 001.txt
│   │   └── 002.txt
│   ├── c
│   │   ├── 109.txt
│   │   └── 110.txt
│   └── f
│       ├── 003.txt
│       └── 004.txt
└── B
    ├── e
    │   ├── 111.txt
    │   └── 112.txt
    └── d
        ├── 007.txt
        └── 008.txt
7 directories, 10 files
```
I want to replace/completely overwrite my dest directory with src directory

**Comment by otiai10** [comment]
remove all first, and copy your src
