### ISSUE TITLE
copy.Copy hangs with named pipes

### ISSUE THREAD

**Issue by mudler** [otiai10/copy#47]
It seems that `copy.Copy` is not supporting named pipes, at the moment it  tries to copy it, resulting in the process to hang.

Would you be interested in accepting a PR to reproduce the named pipe in the given destination ?

**Comment by otiai10** [comment]
Thank you for your feedback!
It makes sense for me and I've got your point.
It seems good time to start discussion on the design of `v2`, and we can put this on that. What do you think?

Though I can see your commit referencing to this issue, your PR would be super appreciated!! 🥰

**Comment by mudler** [comment]
> Thank you for your feedback!
> It makes sense for me and I've got your point.
> It seems good time to start discussion on the design of `v2`, and we can put this on that. What do you think?

Makes sense :slightly_smiling_face:
> 
> Though I can see your commit referencing to this issue, your PR would be super appreciated!! smiling_face_with_three_hearts

Alright then :smile_cat: probably won't be able to work on it today, but I'll open a PR asap among the lines of my commit, but I would avoid to apply permission changes, because likely would need #48 on top

**Comment by mudler** [comment]
@otiai10 opened up https://github.com/otiai10/copy/pull/50 to address this issue! :slightly_smiling_face:  :+1:

**Comment by otiai10** [comment]
Published under [v1.5.0](https://github.com/otiai10/copy/releases/tag/v1.5.0).
Thank you for your insight and contribution ❤️
