### ISSUE TITLE
Handling owner permissions

### ISSUE THREAD

**Issue by mudler** [otiai10/copy#48]
First of all, thanks for the great lib ;)

It would be really nice if copy would handle (with an option, maybe) the owner permission of the resulting file - especially when it's recreating the target (symlink, or namedpipe, see also #47)

Cheers

**Comment by otiai10** [comment]
Thanks again!

At my first view, it's gonna be like `PreserveOwner bool` or something.
Do you think that's what you want, or do we need more customizable action for ownership?

**Comment by mudler** [comment]
> Thanks again!
> 
> At my first view, it's gonna be like `PreserveOwner bool` or something.

Sounds good here! :+1: 

> Do you think that's what you want, or do we need more customizable action for ownership?

I think that's fine (at least for my use-cases) better to follow a KISS approach here, I think that an user if need a more customizable action can just apply the desired ownership after the file gets copied

**Comment by fb913bf0de288ba84fe98f7a23d35edfdb22381** [comment]
I encountered the UID/GID preservation problem with kaniko, which uses this library for copying files/directories. I tested the patch by @mudler linked above by rebuilding the kaniko docker image with a patched version of this library. I now see UIDs/GIDs being preserved as expected. So from my side the patch works great, thank you!

**Comment by otiai10** [comment]
Thank you for leaving comment @fb913bf0de288ba84fe98f7a23d35edfdb22381.

Regarding I couldn't take time for `v2` project, I would like to merge @mudler's patch into this project, if it's ok for @mudler #67

**Comment by fb913bf0de288ba84fe98f7a23d35edfdb22381** [comment]
Awesome, thank you very much for the quick resolution!

**Comment by otiai10** [comment]
published as v1.7.0
