### ISSUE TITLE
How does this differ from https://github.com/golang/dep/blob/v0.5.4/internal/fs/fs.go#L175

### ISSUE THREAD

**Issue by quackduck** [otiai10/copy#51]
Have a look at: https://github.com/golang/dep/blob/v0.5.4/internal/fs/fs.go#L175

How different are `copy.Copy()` and `renameByCopy()`?

**Comment by otiai10** [comment]
As far as I understand it,

* `copy.Copy` handles more types of file entries, such as symlinks.
* `copy.Copy` can add permissions (and ownership coming soon) of destination files.
* `fs. renameByCopy` removes all source files copied (the thing you should compare with is [`fs.CopyDir`](https://github.com/golang/dep/blob/v0.5.4/internal/fs/fs.go#L356), just I guess).
* `copy.Copy` provides some [additional options](https://github.com/otiai10/copy/blob/main/options.go#L5-L35).
* more than all, `dep/internal/fs` is internal and `dep` is deprecated.

Let me know your thought.

**Comment by otiai10** [comment]
@quackduck I will close this issue if no any reply

**Comment by quackduck** [comment]
Sorry, I forgot to say: Oh okay!
