### ISSUE TITLE
Option to copy two or more files simultaneous

### ISSUE THREAD

**Issue by ManuelReschke** [otiai10/copy#81]
hi, is it possible to add an option to copy two or more files simultaneous?
I think this would be an amazing performance boost on the most systems.

What do you think?

**Comment by Techno-Fox** [comment]
Are you talking about passing multiple sources, and destinations at a time? Or using go routines for each?

**Comment by ManuelReschke** [comment]
I talk about go routines. For example, if you copy the path /xy/ you know the folder contains 10 files. And now you copy X files simultaneously with goroutines. Most systems use SSDs and this would increase the overall performance extreme.
