### ISSUE TITLE
Deep symlink copy doesn't work with relative `../foo` target

### ISSUE THREAD

**Issue by samuel-phan** [otiai10/copy#97]
Deep symlink copy will fail in this situation:

```
test
├── data
│   ├── case00
│   │   └── README.md
│   ├── case01
│   │   └── README.md
│   ├── case02
│   │   └── README.md
│   ├── case03
│   │   ├── README.md
│   │   ├── case01 -> test/data/case01
│   │   └── relative_case01 -> ../case01
```

Though it's entirely acceptable to have a symlink working only at a certain current working dir, most of the time, we have symlinks:
- either to an absolute path
- or relative to itself (eg `../something`). 🐛 **This case doesn't work properly.**

**Comment by kernel164** [comment]
<img width="1490" alt="Screenshot 2023-11-13 at 9 51 28 PM" src="https://github.com/otiai10/copy/assets/1174098/f6a25260-7037-4087-bc0a-509beda44c8b">

changing from os.Readlink to filepath.EvalSymlinks worked in my local.
